### ISSUE TITLE
Chinese characters are not shown in Magisk manager.

### ISSUE THREAD

**Issue by alesky** [Magisk-Modules-Repo/magisk-privileged-api-booter#1]
Device: OnePlus 3T on Resurrection Remix latest official build. 
System language: English. 
Probably you can consider using English descriptions.

**Comment by alesky** [comment]
Screenshot attached. 
http://imgur.com/lxfU7vM

**Comment by simonsmh** [comment]
这个算是Magisk Manager的bug了吧
先暂时改回来好了
