### ISSUE TITLE
这个模块怎么用？

### ISSUE THREAD

**Issue by ousui** [Magisk-Modules-Repo/magisk-privileged-api-booter#3]
装了以后不会用，是可以配合黑域自动启动吗？

**Comment by simonsmh** [comment]
开启root模式+关闭root自启动

**Comment by ousui** [comment]
@simonsmh 因为付费不够，目前默认 root 自动启动就是关闭的。
安装模块重启以后，还是需要手动启动一下。
一加五，装了 magisk 肯定是已经 root 啦。

**Comment by simonsmh** [comment]
先付钱，谢谢

**Comment by ousui** [comment]
@simonsmh 
等下个版本再说吧，2.2.6 版本提示『环境不安全，暂不支持支付』……
可以简单举例说下这个模块的功能嘛？现在有点看不懂。
谢谢。

**Comment by simonsmh** [comment]
大致就是可以减少一个用户自己开机启动的操作，有些时候开机广播会被其他软件拦截掉，从而没有软件自启的动作，而一些使用提权API的软件却十分必要而不可或缺，所以我设计了一个这样的模块来手动启动它们，这样就不用在开机时再做重复的操作了

**Comment by ousui** [comment]
@simonsmh 
感谢！
