### ISSUE TITLE
只有存储重定向工作正常

### ISSUE THREAD

**Issue by MichaelPanPRC** [Magisk-Modules-Repo/magisk-privileged-api-booter#3]
原先Shizuku、黑域、存储重定向都用的Magsik Root。安装这个模块后把他们三个的root权限全禁用了，重启后只有存储重定向可以正常使用，其余两个都是授权失败。把那两个的root权限开启后重启，都可以用，但都是走的root，没有走adb。

**Comment by simonsmh** [comment]
root权限应该是必要的，因为手机上没法像adb那样得到更高的shell权限。
不需要的是BOOT_COMPLETED启动完成广播接收器。

**Comment by daiaji** [comment]
能不能把adb直接移植到手机？然后连接本地的adb端口提权？🙄chroot的时候没搞过但我觉得可以
